services:
  - type: web
    name: mana-daakuu
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5

        